# Generated by Django 4.2.5 on 2023-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Usuario')),
                ('username', models.CharField(max_length=255, verbose_name='Nombre de Usuario')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('cell_number', models.CharField(max_length=10, unique=True, verbose_name='Telefono Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=130)),
                ('administrator_profile', models.IntegerField(default=0, verbose_name='Perfil Administrador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-created'],
            },
        ),
    ]
