# Generated by Django 4.2.5 on 2023-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='administrator_profile',
            field=models.BooleanField(default=False, verbose_name='Perfil Administrador'),
        ),
    ]
