# Generated by Django 4.2.5 on 2023-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(default='Sin marca', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(default='Proveedor Desconocido', max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
    ]
