# Generated by Django 4.2.5 on 2023-10-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_medicine_brand_medicine_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Proveedor'),
        ),
    ]
