# Generated by Django 4.2.5 on 2023-10-17 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_remove_patient_username'),
        ('medicamentos', '0003_alter_medicine_brand_alter_medicine_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha Cita')),
                ('symptoms', models.TextField(verbose_name='Sintomas')),
                ('total_price', models.FloatField(verbose_name='Precio Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Medico Asignado')),
                ('medicines', models.ManyToManyField(to='medicamentos.medicine', verbose_name='Medicamentos')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-created'],
            },
        ),
    ]
